<?php

/**
 * @file
 * Contains google_youtube_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function google_youtube_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the google_youtube_api module.
    case 'help.page.google_youtube_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('YouTube api integration module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function google_youtube_api_theme() {
  return [
    'google_youtube_api' => [
      'render element' => 'children',
    ],
  ];
}
